# Generated by Django 2.1.7 on 2019-02-26 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_test',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete='SET_NULL', related_name='category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(blank=True, on_delete='SET_NULL', related_name='category_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
