# Generated by Django 2.1.7 on 2019-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190228_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ManyToManyField(related_name='product_producer', to='product.Producer', verbose_name='Производитель'),
        ),
    ]
