# Generated by Django 2.1.7 on 2019-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190228_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='category',
        ),
        migrations.AddField(
            model_name='producer',
            name='category',
            field=models.ManyToManyField(related_name='producer_category', to='product.Category', verbose_name='Категория'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer',
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(default=0, on_delete='Cascade', related_name='product_producer', to='product.Producer', verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
