# Generated by Django 2.1.7 on 2019-02-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190228_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
